### PR TITLE
Remove status check

### PR DESCRIPTION
**Pull request by rintcius**
[ch12211]

### CODE REVIEW

**Comment by rintcius** [comment]
The change is not that exciting but looking for feedback if you see any problems with the approach - to avoid wasting time when making similar changes for all other destinations.

**Comment by rintcius** [comment]
General idea is that it should be possible to create and edit configs with invalid data (although malformed data still needs to be rejected) and that plugins shouldn't actually connect to the destination when creating/modifying. 

Furthermore, the current error reporting that happens on push doesn't need to change.

Do you see any scenarios where removing the checks here could cause issues? From what I have tested it all looks fine, but want to check if I haven't missed anything.

**Review by cryogenian — APPROVED** [review]
Looks very straightforward and I can't see any problems with this approach

**Comment by wemrysi** [comment]
@rintcius 

> General idea is that it should be possible to create and edit configs with invalid data

While the approach should work for this plugin, it seems like a rather indirect way to achieve the stated goal, in general. Have we considered a more first-class approach where plugin management in quasar is modified to support the desired behavior?

**Comment by jsantos17** [comment]
@rintcius could we instead add an `isLive` method to destination modules? That way sdbe can choose when to do the liveness check. I'm wary about removing the liveness check entirely, since it's a pretty bad experience to create a destination and only realize it's broken/has bad credentials when you try to push.

**Comment by rintcius** [comment]
@wemrysi @jsantos17 

An alternative I thought of is to add a flag to the API indicating whether the liveness check needs to be done or not, so in that way users can choose whether they want to test the connection or not. 

Not sure if that's worth it or not though and haven't thought about how that flag would propagate to quasar exactly. Becky mentioned that the behaviour of this PR is fine for v1 of this epic and it would involve less work, so my thought was to keep it simple for v1 and then decide later how to proceed in v2 and further (where I imagine the check would be readded but offering more flexibility, eg via the flag). I do agree that the better solution is to keep the check around, but from a "provide business value quickly" point of view I went for this.

If you don't like removing the status check, what do think of adding a flag to `POST /datasource` and `PUT /datasource/{id}` like `?checkConnection=true|false`.  Or do you have anything else in mind?

@wemrysi what examples were you thinking exactly that would work out less nice for other destinations than s3?

**Comment by wemrysi** [comment]
@rintcius 

> what examples were you thinking exactly that would work out less nice for other destinations than s3?

This approach should work for existing destinations, I was commenting more from an overall design standpoint. We're implicitly relying on every destination implementation to support instantiation without attempting to connect for this to work consistently. I was thinking we could approach this more explicitly by having plugins expose a configuration validation api so that we can consider the semantics of the config apart from the external environment. We could also use this to convey the expectations of what "valid" means in the types (by say, making the validation api pure). The current signatures include the ability to express these sort of environmental errors at instantiation, so without changing them it is a bit confusing/misleading.

I also like the idea of a separate "test connection" api, separates that concern out nicely 👍

**Comment by jsantos17** [comment]
@rintcius do we still want to do this? or are we keeping it Avalanche-only for now?

**Comment by rintcius** [comment]
@jsantos17 Ah thanks for reminding. Avalanche only, closing this.

**Pull request closed without merging**
